### ISSUE TITLE
SVG version of TodoMVC logo

### ISSUE THREAD

**Issue by robbbz** [tastejs/media#5]

**Comment by sindresorhus** [comment]
https://github.com/tastejs/todomvc/blob/master/media/logo.svg

**Comment by samccone** [comment]
@sindresorhus do you think we should add that file to this repo?

**Comment by sindresorhus** [comment]
No, I intentionally left it out. It's better discovered in the `todomvc` repo and having it here would be messy IMHO.

https://github.com/tastejs/media/commit/3a3082dcf77dfe7667a0c9c68616f471c747cee9

**Comment by samccone** [comment]
kk :+1:
